---
ssh_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHQ43LuXWOH292OD7mFb8kGiP5I93pa1/4tUpkVi9oHq windows-key
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINLc8DcJX2/y8UcfUIvm/IMnh0yY+Z8utE+D6E5Xx9KI Luis's Key wsl
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHluPxOQFsGOGtDwlsAm+sTxCtcAEE5Mt3Tz7UVBow+O ansible control node key