user_map:
  "admin" : { user_id: "1023", home_dir: "/home/admin", user_group: "administrative", group_id: "1999", username: "admin" }
  "podman" : { user_id: "1024", home_dir: "/home/podman", user_group: "development", group_id: "2000", username: "podman" }
  "ansible" : { user_id: "1025", home_dir: "/home/ansible", user_group: "ansible", group_id: "2001", username: "ansible" }
