all:
  vars:
    hostname: idm.home.lab
    extend_mode: var
    wanted_packages:
      - epel-release
      - nc
      - podman
      - vim
      - curl
      - wget
      - git
      - bind-utils
      - tree
      - gcc
      - chrony
      - zip
      - unzip
      - ipa-client
      - python3-pip
      - sshpass
    users:
      - "admin"
      - "ansible"
      #- "podman"

target_hosts:
  children:
    machines:
    
machines:
  hosts:
    10.0.0.100

